from __future__ import annotations

import re
from dataclasses import dataclass
from typing import Iterable


@dataclass(frozen=True)
class ExternalMapping:
    system: str
    identifier: str


@dataclass(frozen=True)
class CanonicalConcept:
    concept_id: str
    concept_type: str
    canonical_name: str
    aliases: tuple[str, ...]
    external_mappings: tuple[ExternalMapping, ...] = ()


@dataclass(frozen=True)
class SemanticRelationship:
    source_id: str
    relationship: str
    target_id: str


@dataclass(frozen=True)
class ResolvedConcept:
    concept_id: str
    concept_type: str
    canonical_name: str
    matched_alias: str
    start: int
    end: int
    confidence: float = 1.0

    def to_dict(self) -> dict:
        return {
            "concept_id": self.concept_id,
            "concept_type": self.concept_type,
            "canonical_name": self.canonical_name,
            "matched_alias": self.matched_alias,
            "start": self.start,
            "end": self.end,
            "confidence": self.confidence,
        }


CONCEPTS: tuple[CanonicalConcept, ...] = (
    CanonicalConcept(
        concept_id="DRUG:ZANUBRUTINIB",
        concept_type="DRUG",
        canonical_name="zanubrutinib",
        aliases=("zanubrutinib",),
    ),
    CanonicalConcept(
        concept_id="BRAND:BRUKINSA",
        concept_type="BRAND",
        canonical_name="BRUKINSA",
        aliases=("brukinsa",),
    ),
    CanonicalConcept(
        concept_id="DRUG:IBRUTINIB",
        concept_type="DRUG",
        canonical_name="ibrutinib",
        aliases=("ibrutinib",),
    ),
    CanonicalConcept(
        concept_id="TRIAL:ALPINE",
        concept_type="CLINICAL_TRIAL",
        canonical_name="ALPINE",
        aliases=("alpine trial", "alpine study", "alpine"),
    ),
    CanonicalConcept(
        concept_id="INDICATION:CLL",
        concept_type="INDICATION",
        canonical_name="chronic lymphocytic leukemia",
        aliases=("chronic lymphocytic leukemia", "cll"),
    ),
    CanonicalConcept(
        concept_id="INDICATION:SLL",
        concept_type="INDICATION",
        canonical_name="small lymphocytic lymphoma",
        aliases=("small lymphocytic lymphoma", "sll"),
    ),
    CanonicalConcept(
        concept_id="TARGET:BTK",
        concept_type="MOLECULAR_TARGET",
        canonical_name="Bruton's tyrosine kinase",
        aliases=("bruton's tyrosine kinase", "bruton tyrosine kinase", "btk"),
    ),
)

RELATIONSHIPS: tuple[SemanticRelationship, ...] = (
    SemanticRelationship("BRAND:BRUKINSA", "BRAND_OF", "DRUG:ZANUBRUTINIB"),
    SemanticRelationship("TRIAL:ALPINE", "EVALUATES", "DRUG:ZANUBRUTINIB"),
    SemanticRelationship("TRIAL:ALPINE", "COMPARES_WITH", "DRUG:IBRUTINIB"),
    SemanticRelationship("TRIAL:ALPINE", "STUDIES_INDICATION", "INDICATION:CLL"),
    SemanticRelationship("TRIAL:ALPINE", "STUDIES_INDICATION", "INDICATION:SLL"),
    SemanticRelationship("DRUG:ZANUBRUTINIB", "TARGETS", "TARGET:BTK"),
    SemanticRelationship("DRUG:IBRUTINIB", "TARGETS", "TARGET:BTK"),
)

CONCEPT_BY_ID = {concept.concept_id: concept for concept in CONCEPTS}

_ALIAS_ROWS = sorted(
    (
        (alias.lower(), concept)
        for concept in CONCEPTS
        for alias in concept.aliases
    ),
    key=lambda item: len(item[0]),
    reverse=True,
)


def get_concept(concept_id: str) -> CanonicalConcept | None:
    return CONCEPT_BY_ID.get(concept_id)


def resolve_mentions(text: str) -> tuple[ResolvedConcept, ...]:
    """Resolve text mentions to canonical pharma concepts.

    Resolution is deterministic and registry-backed. For v1, aliases are curated
    rather than generated by an LLM so ingestion and tests remain reproducible.
    """
    lowered = text.lower()
    best_by_concept: dict[str, ResolvedConcept] = {}
    for alias, concept in _ALIAS_ROWS:
        match = re.search(rf"(?<!\w){re.escape(alias)}(?!\w)", lowered)
        if not match:
            continue
        candidate = ResolvedConcept(
            concept_id=concept.concept_id,
            concept_type=concept.concept_type,
            canonical_name=concept.canonical_name,
            matched_alias=text[match.start():match.end()],
            start=match.start(),
            end=match.end(),
        )
        current = best_by_concept.get(concept.concept_id)
        if current is None or (candidate.end - candidate.start) > (current.end - current.start):
            best_by_concept[concept.concept_id] = candidate
    return tuple(sorted(best_by_concept.values(), key=lambda item: (item.start, item.concept_id)))


def canonical_ids(text: str) -> tuple[str, ...]:
    return tuple(item.concept_id for item in resolve_mentions(text))


def relationships_for_concepts(concept_ids: Iterable[str]) -> tuple[SemanticRelationship, ...]:
    present = set(concept_ids)
    return tuple(
        relation
        for relation in RELATIONSHIPS
        if relation.source_id in present and relation.target_id in present
    )


def related_concept_ids(concept_id: str, include_self: bool = True) -> frozenset[str]:
    related = {concept_id} if include_self else set()
    for relation in RELATIONSHIPS:
        if relation.source_id == concept_id:
            related.add(relation.target_id)
        if relation.target_id == concept_id:
            related.add(relation.source_id)
    return frozenset(related)


def semantic_match(query_text: str, evidence_text: str) -> dict:
    """Return direct and one-hop semantic overlap for retrieval scoring."""
    query_ids = set(canonical_ids(query_text))
    evidence_ids = set(canonical_ids(evidence_text))
    if not query_ids:
        return {
            "score": 0.0,
            "query_concepts": [],
            "evidence_concepts": sorted(evidence_ids),
            "direct_matches": [],
            "related_matches": [],
        }

    direct = query_ids & evidence_ids
    expanded: set[str] = set()
    for concept_id in query_ids:
        expanded.update(related_concept_ids(concept_id, include_self=False))
    related = (expanded & evidence_ids) - direct

    weighted = len(direct) + (0.7 * len(related))
    score = min(1.0, weighted / len(query_ids))
    return {
        "score": round(score, 4),
        "query_concepts": sorted(query_ids),
        "evidence_concepts": sorted(evidence_ids),
        "direct_matches": sorted(direct),
        "related_matches": sorted(related),
    }
